dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh | bash
- touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser
- cd ${TRAVIS_BUILD_DIR}
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- cd packer/
- packer validate -var-file=variables.json.example immutable.json
- packer validate -var-file=variables.json.example ubuntu16.json
- cd ${TRAVIS_BUILD_DIR}/ansible
- ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx
- cd ${TRAVIS_BUILD_DIR}/terraform/stage
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd ${TRAVIS_BUILD_DIR}/terraform/prod
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
notifications:
  slack:
    rooms:
      secure: MkKM3aCku9cNeqmJscy6Wv/2ag7Hh0qxAsl0vJU1wfBT9XQuiHwrQOCzLkqRQT3aM9jdzzoxhZjmgo+GD7XREaVHSZ6iXpVbjIHlzl61fpzQ1ux4jPnXeTKR15Fq8V5EM3ZWxKxfdRRcJe3o1dkcg2bWJ/R/9JG9ergseJczgIdDSVKuZpUc3YhVSPWENdBW4ry85wP6cja9/l6AqV4fbFQo9oM3+OVtSYOjiRc5/i6aCCvpRk/mp3QFhEOe0h+tDLDIufBYAKNEj4Jexcl3otfjVUAtmszBWB/0/lmuMRYFz/BvbUbpjKWtNNH/B3RKIgK8huSM9SOd9p1SMb7PaPkZcOEfQW4bFnpsPG54ofC0eQWeYNsQpURhwPjsAwVm4mleh8jnSleoJOZuvLbrS7m6Nwy2JANLc3iNMSO511O4zwRB2CHqjVkE0QAVHgAExSq9w5xOgEQk4mbFCBdn2HcmzZa6T44/98cSdkjwQnNJ9H5ds/m/lf6Td+p2vSsVLSwfwvDBEA0V7hNc0iIVAA0nx1ZAiIYnsDq8+SL+qjyGlUcKgQJP+D9OfBBkUT97e0R0/KmzWBuRbyXSSPcdS0iQNoq8WWAigw3qDqJ3E0cwmpSaM/y7TzCjZwkwOpI8KuNTJ1TppTG11SLvam8PT9eOb/b4cVViDYc3Ik+wvE0=
