#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_ugrade: true
apt:
  preserve_source_list: true

users:
  name: appuser
  groups: sudo
  shell: /bin/bash
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  ssh-authorized-keys:
   - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmc8hMrIaNSSAQAPYF8mvvv0owaS10PvUbeHQYn1riTBY0GuLVyWzjuMuNRbV4dORkA7sfABc67/wmA06iLCbOpK2ZDFmFyC+ZhlomgchCumfuXSt2ozCDmC2upwt/PqVyFpert4RuS+bldADDJpWj0vOMNNajXNuJMPAg3a/gUR7mW0qWkgGPL6sdsv+SBWf97NMT/JuEdpJo4RCdqjdHUDIrGUV9oeL2ggH6Qqs9GH4n93yD5eAAwByKm51aoekjuBNIhsCtPsOdOMmBjAHVBBqCSIagbD/5R7Qq/PVQSIQvERJVN6qVH6KKaZFyReI6hmIzCmyjC0zeySfyj3Cx root@localhost.localdomain

packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - git
  - apt-transport-https
  - ca-certificates

runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - apt-get install apt-transport-https ca-certificates
  - apt-get update
  - apt-get install -y mongodb-org
  - systemctl start mongod
  - systemctl enable mongod
  - cd /home/appuser
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit && bundle install
  - puma -d
