#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_ugrade: true
apt:
  preserve_source_list: true

users:
  name: appuser
  groups: sudo
  shell: /bin/bash
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  ssh-authorized-keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfRuCnx1PxmJek4mv+So7f/cXvPjjmcbCym37ioEkXkAa+lcHQzkUw+ejBdpMYaiWUN6gfEi2VoidYt0eaAOMeLiqrMJbWHtpYqelPg5Y8/hlUDMh2RvIEXdFGdbSEPGw8x3XENdpOemJFibD82ZMyjvcBSUJOsieGkeo9JTWWS6dpG2fI1PRuMqcE6VN313r1GVrxU8VxlgT0sTx/4+zu/8QyIh7krNn3uvzDjtYMRfHPCegKpQ1qlklljucYi2ZAjqgaY+OKXoQvX6EQSggGU7NVzQhly07ZOZZgEOOeR1Vx2hYEq4dzpSUhQ6MvuAS15LBIBV0nimFDR77XMmYN appuser

packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - git

runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - apt-get install apt-transport-https ca-certificates
  - apt-get update
  - apt-get install -y mongodb-org
  - systemctl start mongod
  - systemctl enable mongod
  - cd /home/appuser
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit && bundle install
  - puma -d
